language: c

sudo: true

before_install:
- |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      apt-cache search libboost-system
      # remove existing cmake install
      sudo apt-get remove -qq cmake cmake-data
      CMAKE_URL="https://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz"
      mkdir cmake3.3 && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake3.3
      export PATH=${PWD}/cmake3.3/bin:${PATH}
    fi
- cmake --version

matrix:
  include:

    - os: linux
      compiler: gcc-4.8
      addons:
        apt:
          packages:
            - g++-4.8
            - cmake
            - libboost-dev
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make

    - os: osx
      compiler: clang
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make
